services:
  - type: web
    name: whatsapp-chatbot
    env: java
    plan: free
    branch: main
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/Project-1-0.0.1-SNAPSHOT.jar
